# fly.toml app configuration file generated for agenda-client-silent-paper-3570 on 2023-11-25T16:53:30+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "awesome-agenda-cw"
primary_region = "ams"

[build]
  dockerfile = "Agenda-client/Dockerfile"


[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
