name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install server dependencies
        run: cd server && npm ci

      - name: Run server tests
        run: cd server && npm test

      - name: Install client dependencies
        run: cd Agenda-client && npm ci

      - name: Run client tests
        run: cd Agenda-client && npm test
